config/routes.rb
Blog::Application.routes.draw do
  resources :posts
  resources :categories
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'

  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/new',     to: 'posts#new',          via: 'get'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  validates :title, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  extend FriendlyId
  friendly_id :title, use: :slugged
  default_scope -> { order('created_at DESC') }

  validates :title, presence: true, uniqueness: true
  validates_presence_of :content, :slug, :category_id

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates(:name, presence: true, length: { maximum: 50})
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :signed_in_user,  only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user,      only: [:new, :create, :edit, :update, :destroy]

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.paginate(page: params[:page])
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted."
    redirect_to posts_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to root_url, notice: "Insufficient privileges for action."
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :signed_in_user,  only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user,      only: [:new, :create, :edit, :update, :destroy]

  def show
    @post = Post.friendly.find(params[:id])
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      @categories = Category.all
      render 'new'
    end
  end

  def destroy
    Post.friendly.find(params[:id]).destroy
    flash[:success] = "Post deleted."
    redirect_to posts_path
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(user_params)
      flash[:success] = "Post edited"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
    @categories = Category.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to root_url, notice: "Insufficient priveleges for action."
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "A Repository of Things"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.submit "Create category", class: "btn btn-default" %>

app/views/categories/new.html.erb
<% provide(:title, 'New Category') %>
<row>
  <div class="span8 offset2">
    <h1>New Category</h1>

    <%= form_for(@category) do |f| %>
        <%= render 'fields', f: f %>
    <% end %>


  </div>
</row>

app/views/categories/show.html.erb
<% provide(:title, @category.title) %>

<div class="container">
    <row>
      <%= render 'shared/sidebar', categories: @categories %>
      <div class="span8">

        <h2> <%= @category.title %></h2>
        <p><%= link_to "delete category", @category, method: :delete, data: { confirm: "You sure?" } %></p>

        <% if @category.posts.any? %>
            <%= will_paginate @posts %>

            <ul class="posts">
              <%= render @posts %>
            </ul>

            <%= will_paginate @posts %>
        <% else %>
            No posts in this category.
        <% end %>
      </div>
    </row>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-fixed-bottom">
  <nav>
    <ul>
      <li><%= link_to "collection", posts_path %></li>
      <li><%= link_to "about rita zevallos", '/posts/1' %></li>
      <% if signed_in? %>
        <li><%= link_to "new post", new_path %></li>
        <li><%= link_to "sign out", signout_path, method: "delete" %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<div class="container">
    <%= yield %>
  </div>
<%= render '/layouts/footer' %>
</body>
</html>

app/views/posts/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :content %>
<%= f.text_area :content %>

<%= f.label :category_id %>
<%= f.collection_select :category_id, @categories, :id, :title%>
<p><%= link_to 'New category', 'categories/new' %>    </p>

<%= f.submit "Create post", class: "btn btn-default" %>

app/views/posts/_post.html.erb
<h1><%= link_to post.title, post %></h1>
<div class="post_info">
  <ul>
    <li>
      <%= post.created_at.strftime("%B %d, %Y") %>
    </li>
    <li>
      in <%= link_to post.category.title, post.category %>
    </li>
    <% if signed_in? && current_user.admin? %>
    <li>
      <%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
    </li>
    <li>
      <%= link_to "edit", edit_post_path(post) %>
    </li>
    <% end %>
  </ul>
</div>

<div class="content">
  <%= simple_format(post.content.html_safe) %>
</div>

app/views/posts/edit.html.erb
<row>
  <div class="span8 offset2">

    <% provide(:title, "Edit post: #{@post.title}") %>
    <h1>Edit post: <%= @post.title %></h1>

    <div class="row">
      <div class="span6 offset3">
        <%= form_for(@post) do |f| %>
            <%= render 'fields', f: f %>
        <% end %>

      </div>
    </div>

  </div>
</row>

app/views/posts/index.html.erb
<% provide(:title, 'The Collection') %>

<row>

  <%= render 'shared/sidebar', categories: @categories %>
  <div class="span8">
    <h2>the collection</h2>

    <%= will_paginate %>

    <ul class="posts">
      <% @posts.each do |post| %>
          <li>
            <%= render post %>
          </li>
      <% end %>
    </ul>

    <%= will_paginate %>
  </div>
</row>

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>
<row>
<div class="span8 offset2">
  <h1>New Post</h1>

    <%= form_for(@post) do |f| %>
        <%= render 'fields', f: f %>
    <% end %>


  </div>
</row>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<div class="container">
  <div class="span8 offset2">
    <%= render @post %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_sidebar.html.erb
<aside class="span2">
  <%= link_to image_tag('plant.png'), root_url %>
  <section>
    <h4>categories</h4>
    <ul>
        <% @categories.each do |cat| %>
            <li><%= link_to cat.title, cat %></li>
        <% end %>
    </ul>
  </section>
</aside>

app/views/static_pages/about.html.erb
<% provide(:title,'Rita Zevallos') %>

<div class="container">
  <div class="span6 offset3">
    <h1>
      This website is really a collection of notes for a research project.
    </h1>
    <p>
      Except I don't know yet what I am researching.
      I know that it is important.
      Somehow it will all tie together in the end.
    </p>

    <p>
      My name is Rita Zevallos. I am a twenty-year-old person studying math,
      computer science, and art at Swarthmore College. I've taken classes in
      psychology, computer science, Spanish, philosophy, English literature,
      Spanish literature, math, physics, studio art, sociology, history, and film.
      I've spent two summers doing math research. I spent a semester studying
      abroad in Madrid. I read a lot of books.
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
<div class="span6" style="padding-top: 50px">
  <%= image_tag("girl-and-plant.png", alt: "repository of images.") %>
</div>
<div class="span3">
  <h1>
    This is some kind of repository of things.
  </h1>
  <p>
    A place I go when my mind needs to spill.
    I learn things. I think things. I make things. Then I forget it all again, and they are gone.
    Where do they go? Each of these paper boxes is tied by invisible string to some point in space-time.
    Although I carry myself with me enclosed in my skin, I am spread all over the universe,
    both the real one and the multitude of imaginary ones.
  </p>
</div>
</div>